---
title: "Welcome to DATA606!"
author: "Jason Bryer"
date: 2020-01-16
draft: false
categories: ["R"]
tags: ["Annoucement"]
---

Welcome to DATA606! My name is Dr. Jason Bryer and I will be your instructor for this semester. In addition to teaching this course, I am Principal Investigator of a Department of Education grant to develop a Diagnostic Assessment and Achievement of College Skills (see [www.DAACS.net](https://www.DAACS.net) for more information) and a Research Data Associate at Cornell University. Couple of important notes as you get started:

* The course syllabus located here: https://fall2020.data606.net I will post all course materials there. Blackboard will be used primarily for submitting assignments.
* [Join the Slack channel by clicking here](https://join.slack.com/t/data606fall2020/shared_invite/enQtOTIzOTM0NzYwMDM5LTRhYzIzODRlOWZkZmUwMGVhZGMzYmE0NDkxYzc0MzA5NGVmMjc0MmRjZTIzMGM3ZjI0NTkzYjVmNjhhOTM3Nzc). This will be our primary mode of communication. For private communications, you can either send private Slack messages or email me at [jason.bryer@sps.cuny.edu](mailto:jason.bryer@sps.cuny.edu).
* Introduce yourself in the Getting Acquainted forum on Blackboard.
* Once you go through the syllabus, try starting Lab 1 as soon as you can. This will require you to install R and RStudio and will help get you get acquainted with R.
* The best way to reach me is by Slack or email at [jason.bryer@sps.cuny.edu](mailto:jason.bryer@sps.cuny.edu). If you would prefer to talk on the phone or setup a Zoom session, it is best to suggest some times by email first.
* Our meetups will be on Wednesdays from 8:30pm to 9:30pm.
* I am looking forward to getting to know everyone and a fantastic semester! Good luck!


<!-- iframe width="560" height="315" src="https://www.youtube.com/embed/yIyferBnO24" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe -->

<!-- iframe src="/slides/2019-01-24-Intro_to_Course.html#1" width="1024px" height="768px"  frameborder="0" allowfullscreen>
</iframe -->
