fl.counties <- c('ALACHUA',
				 'BAKER',
				 'BAY',
				 'BRADFORD',
				 'BREVARD',
				 'BROWARD',
				 'CALHOUN',
				 'CHARLOTTE',
				 'CITRUS',
				 'CLAY',
				 'COLLIER',
				 'COLUMBIA',
				 'MIAMI-DADE',
				 'DESOTO',
				 'DIXIE',
				 'DUVAL',
				 'ESCAMBIA',
				 'FLAGLER',
				 'FRANKLIN',
				 'GADSDEN',
				 'GILCHRIST',
				 'GLADES',
				 'GULF',
				 'HAMILTON',
				 'HARDEE',
				 'HENDRY',
				 'HERNANDO',
				 'HIGHLANDS',
				 'HILLSBOROUGH',
				 'HOLMES',
				 'INDIAN RIVER',
				 'JACKSON',
				 'JEFFERSON',
				 'LAFAYETTE',
				 'LAKE',
				 'LEE',
				 'LEON',
				 'LEVY',
				 'LIBERTY',
				 'MADISON',
				 'MANATEE',
				 'MARION',
				 'MARTIN',
				 'MONROE',
				 'NASSAU',
				 'OKALOOSA',
				 'OKEECHOBEE',
				 'ORANGE',
				 'OSCEOLA',
				 'PALM BEACH',
				 'PASCO',
				 'PINELLAS',
				 'POLK',
				 'PUTNAM',
				 'ST. JOHNS',
				 'ST. LUCIE',
				 'SANTA ROSA',
				 'SARASOTA',
				 'SEMINOLE',
				 'SUMTER',
				 'SUWANNEE',
				 'TAYLOR',
				 'UNION',
				 'VOLUSIA',
				 'WAKULLA',
				 'WALTON',
				 'WASHINGTON')
